version: '3'

networks:
  inception-network:

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    #image: img_nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "~/Desktop/inception/website:/var/www/html"
    networks:
      - inception-network
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    # image: img_wordpress
    volumes:
      - "~/Desktop/inception/website:/var/www/html"
    networks:
      - inception-network
    environment: 
      - WP_URL=${WP_URL}
      - WP_DATABASE=${WP_DATABASE}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PWD=${WP_ADMIN_PWD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_PWD=${WP_USER_PWD}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PWD=${MARIADB_PWD}
      - MARIADB_DB=${MARIADB_DB}
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    # image: img_mariadb
    ports:
      - "3306:3306"
    volumes:
      - "~/Desktop/inception/mariadb:/var/lib/mysql"
    networks:
      - inception-network
    environment:
      - MARIADB_ROOT_PWD=${MARIADB_ROOT_PWD}
      - MARIADB_DB=${MARIADB_DB}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PWD=${MARIADB_PWD}
    restart: always

# volumes:
#   mariadb-volume:
#     driver: local
#     driver_opts:
#       device: /home/malatini/data/database
#       type: volume
#       o: bind
#   wordpress-volume:
#     driver: local
#     driver_opts:
#       device: /home/malatini/data/wordpress
#       type: volume
#       o: bind